[broker]
host = localhost
port = 1883
username = mqtt_user
password = your_password


[login]
username = sgfgsadg
password = 2345r3g34
secret_key = 343456nghjgyjgf4534


[other]
iot_proxy_web=http://192.168.31.84:5000